FROM python:latest

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

COPY . /usr/src/app
#RUN apt-get update && apt-get install -y python3-pip python3
CMD ["python", "main.py"]x nbvcdxszaa drftgyH
":lKJUIO89U